import { GlyphRaster, FontRaster } from "../models";

const version = process.env.npm_package_version;

export const versionString = `v${version}`

export const fileDescriptor = (font: FontRaster) => [
  font.outputName,
  "",
  `Auto-generated by ttf2c.js:`,
  `  Version: ${versionString}`,
  `  Font:    ${font.fontName}`,
  `  Glyphs:  ${font.glyphs.length} / ${font.totalFontGlyphs}`
];

export const indent = (by: number) => (level: number) => (line: string) =>
  "".padStart(by * level, " ") + line;

export const addCommas = (lines: Array<string>) =>
  lines.join(",\n").split("\n");

export const toCodePointHex = (c: number) =>
  "U+" + c.toString(16).padStart(4, "0");

export const toCodePointName = (c: number) =>
  String.fromCodePoint(c)

export const toCodePointDescription = (c: number) =>
  `${toCodePointHex(c)} "${toCodePointName(c)}"`

const toByteDisplay = (byte: number) =>
  byte > 0 ? "█" : " ";

export const toBox = (minWidth: number) => (lines: Array<string>) => {
  const max = (a: number, b: number) => Math.max(a, b)
  const width = lines.map(l => l.length).reduce(max, minWidth);
  const end = "+" + "".padEnd(width + 2, "-") + "+";
  const middle = lines.map(l => "| " + l.padEnd(width, " ") + " |");
  return [end, ...middle, end];
}

export const glyphFormatter = (glyph: GlyphRaster) => {
  return {
    codePointHex: () => toCodePointHex(glyph.codePoint),
    quotedName: () => `"${glyph.name}"`,
    size: () => `${glyph.width}x${glyph.height}`,
    offset: () => `(${glyph.xOffset}, ${glyph.yOffset})`,

    pixelDisplay: () => glyph.pixels.map(row => row.map(toByteDisplay).join("")),

    description: () => `${toCodePointHex(glyph.codePoint)} "${glyph.name}"`
  }
};